[project]
name = "aiskolprov"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "datasets>=4.0.0",
    "openai>=1.99.9",
    "pandas>=2.3.1",
    "tqdm>=4.67.1",
]
